# Generated by Django 3.2.9 on 2022-07-30 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/categories')),
                ('name', models.CharField(max_length=100)),
                ('total_item', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image1', models.ImageField(upload_to='images/products')),
                ('image2', models.ImageField(upload_to='images/products')),
                ('descriction', models.TextField()),
                ('price', models.IntegerField()),
                ('offerprice', models.IntegerField()),
                ('code', models.IntegerField()),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Product.category')),
            ],
        ),
    ]
