# Generated by Django 3.2.9 on 2022-07-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20220730_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trendy',
            field=models.BooleanField(default=False),
        ),
    ]
