# Generated by Django 3.2.9 on 2022-07-31 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_product_trendy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriction',
            new_name='description',
        ),
    ]
